name: Flutter CI

on: push

jobs:
  build-release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Install project dependencies
        run: flutter pub get
      
      - name: Enable windows build
        run: flutter config --enable-windows-desktop

      #- name: Build flask app
      #  run: dart run serious_python:main package assets/app/

      - name: Build artifacts
        run: flutter build windows
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: BP-Sender-${{github.ref_name}}-windows.zip
          directory: build/windows/x64/runner/Release

      - name: Build installer
        run: dart windows_installer_creator.dart
      
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "rel"
          files: build/windows/x64/runner/Release/BP-Sender-${{github.ref_name}}-windows.zip
